/******************************************************************************
 * ╔═══════════════════════════════════════════════════════════════════════╗ *
 * ║                                                                       ║ *
 * ║   WARNING: AUTO-GENERATED FILE                                        ║ *
 * ║                                                                       ║ *
 * ║   This file is automatically generated by SAP Fiori tools and is      ║ *
 * ║   overwritten when you run the OPA test generator again.              ║ *
 * ║                                                                       ║ *
 * ║   To add your own custom tests:                                       ║ *
 * ║   - Create a new journey test file in this directory.                 ║ *
 * ║   - Follow the same pattern as this file.                             ║ *
 * ║   - Add the new file to the opaTests.qunit.js config file.            ║ *
 * ║   - Custom journey files are not overwritten.                         ║ *
 * ║                                                                       ║ *
 * ╚═══════════════════════════════════════════════════════════════════════╝ *
 ******************************************************************************/

sap.ui.define([
    "sap/ui/test/opaQunit",
    "./pages/JourneyRunner"
], function (opaTest, runner) {
    "use strict";

    function journey() {
        QUnit.module("EmployeesObjectPageObjectPage journey");

        opaTest("Navigate to EmployeesObjectPageObjectPage", function (Given, When, Then) {
            Given.iStartMyApp();
            When.onTheEmployeesListGenerated.onFilterBar().iExecuteSearch();
            Then.onTheEmployeesListGenerated.onTable().iCheckRows();
            When.onTheEmployeesListGenerated.onTable().iPressRow(0);

            Then.onTheEmployeesObjectPageGenerated.iSeeThisPage();
        });



        opaTest("Check the GeneratedFacet1 section of the Object Page", function (_Given, _When, Then) {
            Then.onTheEmployeesObjectPageGenerated.iCheckSection({ section: "GeneratedFacet1" });
            Then.onTheEmployeesObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "employeeName" });
            Then.onTheEmployeesObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "employeeEmail" });
            Then.onTheEmployeesObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "employeeDepartment" });
            Then.onTheEmployeesObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "employeeDesignation" });
            Then.onTheEmployeesObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "employeeJoiningDate" });
            Then.onTheEmployeesObjectPageGenerated.onForm({ section: "GeneratedFacet1" }).iCheckField({ property: "employeeCount" });
        });

        opaTest("Teardown", function (Given, When, Then) { 
            // Cleanup
            Given.iTearDownMyApp();
        });
    }

    runner.run([journey]);
});